"""Mesh-independent observables reconstructed from a stored spectrum.

These helpers implement the compact formulas from ``DESIGN.md §10.2``. They only
depend on the eigenpairs stored in :class:`lax.spectral.types.Spectrum`, so they can
be reused by both the public spectral API and the solver-bound observable wrappers.
"""

from __future__ import annotations

import jax
import jax.numpy as jnp

from lax.spectral.types import Spectrum


def rmatrix_from_spectrum(
    spectrum: Spectrum,
    energy: float | jax.Array,
    channel_radius: float,
    mass_factor: float,
) -> jax.Array:
    """Return the Wigner-Eisenbud R-matrix. [DESIGN.md §10.2]

    Parameters
    ----------
    spectrum
        Stored eigensystem of the Bloch-augmented Hamiltonian.
    energy
        Physical energy in MeV. The helper converts it to the library's fm^-2
        convention before forming the spectral denominator.
    channel_radius
        Channel radius ``a`` used in the surface-amplitude normalization.
    mass_factor
        Conversion factor ``ℏ² / 2μ`` in MeV fm².

    Returns
    -------
    jax.Array
        Channel-space R-matrix evaluated at ``energy``.
    """

    surface_amplitudes = spectrum.surface_amplitudes
    denominator = _spectral_denominator(spectrum, energy, mass_factor)
    matrix: jax.Array = (
        jnp.einsum(
            "m,mc,md->cd",
            denominator,
            surface_amplitudes,
            surface_amplitudes,
        )
        / channel_radius
    )
    return matrix


def greens_from_spectrum(
    spectrum: Spectrum,
    energy: float | jax.Array,
    mass_factor: float,
) -> jax.Array:
    """Return the resolvent ``(H - E / mass_factor)^-1``. [DESIGN.md §10.2]

    Parameters
    ----------
    spectrum
        Stored eigensystem of the Bloch-augmented Hamiltonian.
    energy
        Physical energy in MeV.
    mass_factor
        Conversion factor ``ℏ² / 2μ`` in MeV fm².

    Returns
    -------
    jax.Array
        Matrix resolvent reconstructed from the stored eigenpairs.

    Raises
    ------
    ValueError
        If the spectrum was compiled without eigenvectors.
    """

    eigenvectors = spectrum.eigenvectors
    if eigenvectors is None:
        msg = "Green's function evaluation requires stored eigenvectors."
        raise ValueError(msg)

    denominator = _spectral_denominator(spectrum, energy, mass_factor)
    transpose = _spectral_metric_transpose(spectrum, eigenvectors)
    # Hermitian spectra use the usual ``U diag U†`` reconstruction, while the
    # complex-symmetric path follows the ``U diag U^T`` metric from DESIGN.md §10.2.
    matrix: jax.Array = (eigenvectors * denominator[None, :]) @ transpose
    return matrix


def wavefunction_internal_from_spectrum(
    spectrum: Spectrum,
    energy: float | jax.Array,
    source: jax.Array,
    mass_factor: float,
) -> jax.Array:
    """Return the internal wavefunction generated by a source term.

    Parameters
    ----------
    spectrum
        Stored eigensystem of the Bloch-augmented Hamiltonian.
    energy
        Physical energy in MeV.
    source
        Mesh-space source vector of shape ``(N_c · N,)``.  Following
        Descouvemont [2] eq. 27, for a reaction driven by an incoming wave in
        channel ``c`` at energy ``E_i``:

        .. code-block:: python

            source[c*N : (c+1)*N] = basis_at_boundary * H_minus[E_i, c]
            # all other blocks are zero

        Use :func:`lax.make_wavefunction_source` to build this automatically
        from a compiled :class:`~lax.Solver`.
    mass_factor
        Conversion factor ``ℏ² / 2μ`` in MeV fm².

    Returns
    -------
    jax.Array
        Internal wavefunction values in the mesh basis.
    """

    greens = greens_from_spectrum(spectrum, energy=energy, mass_factor=mass_factor)
    values: jax.Array = greens @ source
    return values


def _spectral_denominator(
    spectrum: Spectrum,
    energy: float | jax.Array,
    mass_factor: float,
) -> jax.Array:
    """Return ``1 / (ε_k - E / mass_factor)`` in the library unit convention."""

    energy_dimless = energy / mass_factor
    denominator: jax.Array = 1.0 / (spectrum.eigenvalues - energy_dimless)
    return denominator


def _spectral_metric_transpose(spectrum: Spectrum, eigenvectors: jax.Array) -> jax.Array:
    """Return the transpose metric appropriate for the stored eigensystem."""

    return eigenvectors.conj().T if spectrum.is_hermitian else eigenvectors.T


__all__ = [
    "greens_from_spectrum",
    "rmatrix_from_spectrum",
    "wavefunction_internal_from_spectrum",
]
